# Generated by Django 4.2.7 on 2024-01-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_company_name_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.TextField(null=True, verbose_name='自己紹介'),
        ),
    ]
