# Generated by Django 4.2.7 on 2024-01-10 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0003_alter_user_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='事業者名'),
        ),
    ]
