# Generated by Django 4.2.7 on 2024-01-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('空間', '空間'), ('モノ', 'モノ'), ('移動', '移動'), ('スキル', 'スキル')], max_length=40, verbose_name='カテゴリ'),
        ),
    ]
