# Generated by Django 4.2.7 on 2024-01-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('space', '空間'), ('stuff', 'モノ'), ('transportation', '移動'), ('skill', 'スキル')], max_length=40, verbose_name='カテゴリ'),
        ),
    ]
