# Generated by Django 4.2.7 on 2024-01-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetailbasic',
            name='introduction',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetailbasic',
            name='userName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userdetailbusiness',
            name='introduction',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetailbusiness',
            name='serviceName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
