# Generated by Django 4.2.7 on 2024-01-09 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_userdetailbasic_introduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetailbasic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetailbasic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AddField(
            model_name='userdetailbusiness',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetailbusiness',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetailbusiness',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='userdetailbusiness',
            name='introduction',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
    ]
