# Generated by Django 4.2.7 on 2024-01-10 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_userdetailbasic_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetailbasic',
            name='accountName',
        ),
        migrations.RemoveField(
            model_name='userdetailbasic',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userdetailbasic',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='userdetailbasic',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userdetailbusiness',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userdetailbusiness',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userdetailbusiness',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='userdetailbusiness',
            name='serviceName',
        ),
        migrations.RemoveField(
            model_name='userdetailbusiness',
            name='updated_at',
        ),
    ]
